# Redirects
[[redirects]]
  from = "/api/*"
  to = "https://intelli-chat-e9vv.onrender.com/:splat"
  status = 200
  force = true

# Headers
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://intelli-chat.netlify.app"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
