[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://intelli-chat.netlify.app, https://ill-kerchief-lion.cyclic.app"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
